# maybe put under ds preparation?

# dataset:

err_th: 2.0
down_scale: 0.3
in_dirs: ["./dataset/raw_data"]
keys: [""]

#out_dir: "./dataset/var_sizes"
#const_patch_size: null
out_dir: "./dataset/const_size_"
const_patch_size: 33

max_items: null
#ends_with: '.jpg'
ends_with: '.tonemap.jpg'
min_scale_th: 15.0
clean_out_dir: True

train:
    # ("cpu", "gpu", "tpu", "ipu", "hpu", "mps, "auto")
    accelerator: 'cpu'
    gpus: [0]
    batch_size: 32
    grouped_by_sizes: False
    max_epochs: 10
    learning_rate: 0.01
    enable_wandlog: False
    freeze_feature_extractor: False

