# maybe put under ds preparation?

# dataset:
dataset:
    err_th: 2.0
    # scale_ratio_th > 1, scale_ratio \in [1 / scale_ratio_th, scale_ratio_th]
    scale_ratio_th: 4.0

    down_scale: 0.3
    in_dirs: ["./dataset/raw_data"]
    keys: [""]

    #out_dir: "./dataset/var_sizes"
    #const_patch_size: null
    out_dir: "./dataset/const_size_"
    const_patch_size: 33

    max_items: 10
    #ends_with: '.jpg'
    ends_with: '.tonemap.jpg'
    min_scale_th: 15.0
    clean_out_dir: True
    to_grey_scale: True
    half_pixel_adjusted: True

    show_kpt_patches: False
    compare_patches: False


train:
    # ("cpu", "gpu", "tpu", "ipu", "hpu", "mps, "auto")
    accelerator: 'cpu'
    gpus: [0]
    batch_size: 32
    grouped_by_sizes: False
    max_epochs: 10
    learning_rate: 0.01
    enable_wandlog: False
    freeze_feature_extractor: False

